### ISSUE TITLE
Check other functionalities and plugins

### ISSUE THREAD

**Issue by strubrina** [strubrina/WEEM#10]
Nutzt Issues, Tasks, Labels, Milestones, Ganttlab, ein Wiki und mindestens ein Project um euren Projektplan auf Github abzubilden. Darüber hinaus dürfen freiwillig natürlich alle Funktionalitäten oder Plugins, die ihr auf Github findet, verwendet werden (siehe https://github.com/marketplace). 
(Beschreibung Assignment 2)

**Comment by 1212mikeh** [comment]
1. As Picture Quality is crucial for the project, using plug-ins to improve it, could be useful. Imgbot is a possible (and widely-used) option.
- [ ] Test the functions of Imgbot
- [ ] discuss pro & con of the use for the project

2. The Project uses large amounts of data, so faster working scripts would save time. Codacy could be useful for improving the sourcecode.
- [ ] Test the functions of Codacy
- [ ] discuss pro & con of the use for the project

3.  Communication runs mainly via Slack, so the Slack Plugin for github should be used.
- [ ]  install the Plug in for all Project-Members 

4. Doing Project Managment Agenda on Github can cost much time, so using a bot for issue labeling, could improve the Workflow
- [ ]  Try Issue-Label Bot to speed up PM 

5. As we work with agile based management style, Tools like zenhub or zube, could turn out to be usefull.
- [ ] Test both plug ins
- [ ] Discuss pro & con of the use for the project
